package com.github.mrtamm.demo.json;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.util.UUID;

/**
 * User entity type used for JSON responses.
 */
public record UserView(
    @Schema(description = "Person's ID generated by the system")
    @NotNull UUID id,

    @Schema(description = "First name of the person", example = "John")
    @NotBlank @Size(min = 1, max = 100) String firstName,

    @Schema(description = "Person's last name", example = "Smith")
    @NotBlank @Size(min = 1, max = 100) String lastName,

    @Schema(description = "Person's (unique) email", example = "john.smith@example.org")
    @NotBlank @Size(min = 6, max = 100) @Email String email
) {
}
